-- ════════════════════════════════════════════════════════════
-- Transcription Pipeline — Supabase Migration
-- ════════════════════════════════════════════════════════════
-- Run this in the Supabase SQL Editor to create the required table.
-- ════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS transcription_data (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    file_name       text NOT NULL,
    file_size       bigint,
    drive_file_id   text,
    transcript      text,
    summary         text,
    html            text,
    state           text NOT NULL CHECK (
                        state IN ('new', 'transcribed', 'summarized', 'html', 'archived', 'error')
                    )
);

-- Index on state for pipeline queries (recovery, batch filtering)
CREATE INDEX IF NOT EXISTS idx_transcription_data_state
    ON transcription_data (state);

-- Index on created_at for month-based batch queries
CREATE INDEX IF NOT EXISTS idx_transcription_data_created_at
    ON transcription_data (created_at);

-- Index on file_name for filename-based batch queries
CREATE INDEX IF NOT EXISTS idx_transcription_data_file_name
    ON transcription_data (file_name);

-- Trigger to auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_transcription_data_updated_at
    BEFORE UPDATE ON transcription_data
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
