"""HTML email body renderer — converts summary dict to Gmail-safe HTML."""

import logging
from html import escape
from typing import Any

logger = logging.getLogger(__name__)


def render_html(summary: dict[str, Any]) -> str:
    """Render a summary dictionary into a full HTML email body.

    The output uses only inline CSS for Gmail compatibility.

    Parameters
    ----------
    summary : dict
        Parsed summary with keys: meeting_subject, speakers,
        action_items, discussion_topics, resourcing.

    Returns
    -------
    str
        Complete HTML document string.
    """
    meeting_subject = escape(str(summary.get("meeting_subject", "Meeting Summary")))
    speakers = summary.get("speakers", [])
    action_items = summary.get("action_items", [])
    discussion_topics = summary.get("discussion_topics", [])
    resourcing = summary.get("resourcing", [])

    # Build speakers list
    speakers_html = _render_list(speakers)

    # Build action items list
    action_items_html = ""
    if action_items:
        items = []
        for item in action_items:
            if isinstance(item, dict):
                assigned = escape(str(item.get("assigned_to", "Unassigned")))
                action = escape(str(item.get("action", "")))
                items.append(
                    f'<li style="margin-bottom: 6px;">'
                    f'<strong>{assigned}</strong>: {action}</li>'
                )
            else:
                items.append(
                    f'<li style="margin-bottom: 6px;">{escape(str(item))}</li>'
                )
        action_items_html = '<ul style="padding-left: 20px;">\n' + "\n".join(items) + "\n</ul>"
    else:
        action_items_html = '<p style="color: #666;">No action items identified.</p>'

    # Build discussion topics list
    discussion_html = _render_list(discussion_topics)

    # Build resourcing list
    resourcing_html = _render_list(resourcing) if resourcing else (
        '<p style="color: #666;">No resourcing items identified.</p>'
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{meeting_subject}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f9f9f9; font-family: Arial, sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color: #f9f9f9;">
    <tr>
      <td align="center" style="padding: 20px 0;">
        <table role="presentation" width="700" cellpadding="0" cellspacing="0"
               style="max-width: 700px; width: 100%; background-color: #ffffff;
                      border: 1px solid #e0e0e0; border-radius: 8px;">
          <!-- Header -->
          <tr>
            <td style="padding: 30px 30px 20px 30px; border-bottom: 2px solid #4a90d9;">
              <h2 style="margin: 0; color: #333333; font-size: 22px; font-weight: bold;">
                {meeting_subject}
              </h2>
            </td>
          </tr>

          <!-- Speakers -->
          <tr>
            <td style="padding: 20px 30px 10px 30px;">
              <h3 style="margin: 0 0 10px 0; color: #4a90d9; font-size: 16px;
                         text-transform: uppercase; letter-spacing: 0.5px;">
                Speakers
              </h3>
              {speakers_html}
            </td>
          </tr>

          <!-- Action Items -->
          <tr>
            <td style="padding: 10px 30px;">
              <h3 style="margin: 0 0 10px 0; color: #4a90d9; font-size: 16px;
                         text-transform: uppercase; letter-spacing: 0.5px;">
                Action Items
              </h3>
              {action_items_html}
            </td>
          </tr>

          <!-- Discussion Topics -->
          <tr>
            <td style="padding: 10px 30px;">
              <h3 style="margin: 0 0 10px 0; color: #4a90d9; font-size: 16px;
                         text-transform: uppercase; letter-spacing: 0.5px;">
                Discussion Topics
              </h3>
              {discussion_html}
            </td>
          </tr>

          <!-- Resourcing -->
          <tr>
            <td style="padding: 10px 30px 30px 30px;">
              <h3 style="margin: 0 0 10px 0; color: #4a90d9; font-size: 16px;
                         text-transform: uppercase; letter-spacing: 0.5px;">
                Resourcing
              </h3>
              {resourcing_html}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 15px 30px; background-color: #f5f5f5;
                       border-top: 1px solid #e0e0e0; border-radius: 0 0 8px 8px;">
              <p style="margin: 0; color: #999999; font-size: 11px; text-align: center;">
                Generated by Transcription Pipeline
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""

    logger.info("Rendered HTML email (%d chars) for '%s'", len(html), meeting_subject)
    return html


def _render_list(items: list) -> str:
    """Render a simple list of strings as an HTML <ul>.

    Parameters
    ----------
    items : list
        List of strings to render.

    Returns
    -------
    str
        HTML string with <ul>/<li> elements.
    """
    if not items:
        return '<p style="color: #666;">None identified.</p>'

    li_items = [
        f'<li style="margin-bottom: 6px;">{escape(str(item))}</li>'
        for item in items
    ]
    return '<ul style="padding-left: 20px;">\n' + "\n".join(li_items) + "\n</ul>"
